services:
  angular:
    build:
      context: ./angular
      dockerfile: Dockerfile.dev
    ports:
      - "5555:5555"
    volumes:
      - ./angular/:/app
      - /app/node_modules
  svelte:
    build:
      context: ./svelte
      dockerfile: Dockerfile.dev
    ports:
      - "5556:5556"
    volumes:
      - ./svelte/:/app
      - /app/node_modules
