FROM node:20-alpine AS builder

WORKDIR /svelteApp

COPY package.json package-lock.json ./

RUN npm install

COPY . .

RUN npm run build

FROM node:20-alpine AS runner

WORKDIR /svelteApp

RUN npm install -g serve

# Copy built files from the builder stage
COPY --from=builder /svelteApp/dist /svelteApp/dist

# Expose port
EXPOSE 5556

# Run the static server
CMD ["serve", "-s", "dist", "-l", "5556"]
